### ISSUE TITLE
Using this mod breaks spectating

### ISSUE THREAD

**Issue by Hardeh** [Lauriichan/LC-FriendPatches#1] opened 2024-01-15 21:41 UTC
Apparently using this mod breaks spectating - spectator camera randomly freezes in place and you're unable to switch between players. Never happened after i disabled the mod.

**Comment by Lauriichan** [comment] 2024-01-16 09:50
So far me and my friends have used this mod the whole time without any issues, could u provide a list of all mods that you were using?

**Comment by Lauriichan** [comment] 2024-01-19 19:21
Would it be possible for you to provide them? Otherwise I will not be able to reproduce the issue and or fix it.

**Comment by Hardeh** [comment] 2024-01-25 01:01
Sorry, i've kinda forgot i left an issue here. Let me retest and share my modlist if that bug happens again (as there was lots of changes in my modlist since then).
I see in changelog that "Fix Persona updates being made even if player is not in lobby" - i think it may be related exactly to that, as  if i understand correctly mod somehow affect player slots, and in the middle of active match that may be exact reason it breaks. I'll let you know when i'll playtest mod again with my friends.

**Comment by Lauriichan** [comment] 2024-01-25 17:19
I'm pretty sure that the mentioned change is not related as what the change did was ignore persona updates of your friends (in your steam friendlist) that are not in your lobby. Meaning the mod tried to update the name of a person that is not even in your lobby which in the end does nothing as it checks the Steam Id of every player if it matches the person that was just updated by Steam.

**Comment by Hardeh** [comment] 2024-01-25 19:17
Well, yeah, we tried today and it happened again - spectating breaks, freezing camera in place, then after respawning you stuck in the black screen for quite some time and can't hear or see anyone (for other players you're in the ship wall and they can hear you) and then being teleported back to the ship after 10 seconds or so. Also when this happened my morecompany cosmetics disappeared from me.
I attached export file from r2modman with my modpack configuration, so you should be able to recreate this bug, as it's pretty constant.
[Live_1706209965040.zip](https://github.com/Lauriichan/LC-FriendPatches/files/14056967/Live_1706209965040.zip)

**Comment by Lauriichan** [comment] 2024-01-25 19:18
Do you use some VPN or smth?

**Comment by Hardeh** [comment] 2024-01-25 19:19
Nope, no VPN

**Comment by Lauriichan** [comment] 2024-01-25 19:39
Could u try it again but before you do so 
![image](https://github.com/Lauriichan/LC-FriendPatches/assets/41839265/f9daeb8d-0ca0-42ea-840d-5a5a10719857)
Set this to false

**Comment by Hardeh** [comment] 2024-01-25 19:45
Sure, i might be able to test tomorrow

**Comment by Lauriichan** [comment] 2024-01-25 19:46
Also were you the host when playing or just a player?
My guess here is that it might be related to MoreCompany as we're mostly playing Vanilla and with no issues at all

**Comment by Hardeh** [comment] 2024-01-25 19:47
I was host, but it breaks to non-host players just as well

**Comment by Lauriichan** [comment] 2024-01-25 19:47
Okay thanks for that info, I'll look into it soon

**Comment by Lauriichan** [comment] 2024-02-18 14:19
So far I was not able to reproduce this but there might still be a possibility that this is related to some incompatibility

**Comment by Lauriichan** [comment] 2024-03-07 17:46
Might have been fixed with 6b3acbd (1.0.2)

**Comment by Sourceshard** [comment] 2024-03-08 04:21
Ahh I was having this issue as well and was trying to track it down. I will report back if this problem has disappeared for me.

**Comment by Lauriichan** [comment] 2024-03-08 16:42
> Ahh I was having this issue as well and was trying to track it down. I will report back if this problem has disappeared for me.

Could you possibly provide a full mod list so I can check for similarities?

**Comment by Lauriichan** [comment] 2024-03-08 17:29
So I hope that 1.0.3 fixes everything but I highly doubt it.
It could be that there was a small lag / delay because of the 'Recently played with' feature this mod implements for LethalCompany and I hope that by doing this asynchronously as well as changing the name asynchronously might fix it. I can't really tell if it will or will not as so far I have not been able to reproduce this issue in any playthrough since I made this mod.

I'm also not sure if this is related to some incompatibility with another mod so if 1.0.3 doesn't fix it then some more investigation is required. I really don't know how changing the user name and hooking into a callback can break the game so much so in general this whole situation is a big surprise for me but I hope we can all work together in order to find a fix for this issue :)

**Comment by rainbow137** [comment] 2024-03-08 18:13
> > Ahh I was having this issue as well and was trying to track it down. I will report back if this problem has disappeared for me.
> 
> Could you possibly provide a full mod list so I can check for similarities?

After testing with my friend and I, in version 1.0.2 I get this spectator problem even if I turn off the "Play with" option, and in the config file I get this situation:
![7X`2HJTQ3T2JG{Y)(9A3%2S](https://github.com/Lauriichan/LC-FriendPatches/assets/75236377/d833d334-19d5-475b-956c-8b33f4dca8bd)

According to my guess, if there are no issues with the original, it may have something to do with the following two mods: "Morecompany" or "SpectateEnemies"

The camera freeze problem often occurs when observing an enemy or teammate after death, switching back and forth, or looking at the same object for a long time causes the camera to be fixed, which causes the camera to get stuck even after being resurrected

**Comment by rainbow137** [comment] 2024-03-08 18:16
Of course, I think it's likely that the list of observable players or monsters has changed, or that the camera has been fixed frequently?

**Comment by rainbow137** [comment] 2024-03-08 18:26
We're playing with modpacks that are too large to use code or file exports, but I can give you a mods.yml of modpacks

After unzipping, you can browse

[mods.zip](https://github.com/Lauriichan/LC-FriendPatches/files/14541800/mods.zip)

**Comment by Lauriichan** [comment] 2024-03-08 19:56
> > > Ahh I was having this issue as well and was trying to track it down. I will report back if this problem has disappeared for me.
> > 
> > 
> > Could you possibly provide a full mod list so I can check for similarities?
> 
> After testing with my friend and I, in version 1.0.2 I get this spectator problem even if I turn off the "Play with" option, and in the config file I get this situation: ![7X`2HJTQ3T2JG{Y)(9A3%2S](https://private-user-images.githubusercontent.com/75236377/311324551-d833d334-19d5-475b-956c-8b33f4dca8bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Mjc5NzEsIm5iZiI6MTcwOTkyNzY3MSwicGF0aCI6Ii83NTIzNjM3Ny8zMTEzMjQ1NTEtZDgzM2QzMzQtMTlkNS00NzViLTk1NmMtOGIzM2Y0ZGNhOGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE5NTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMTliMTlhNDgyMzQwMDZhMWI5MWQ4OGY5ODQ4MmVjOTQ1MDU0ZjlkZDc5MDI1NzU1MTc3MTNkNzdlYTg3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8gjw50jH1D8DNK2HefdvmxdfK7kTvRJLPtRDN16wWk)
> 
> According to my guess, if there are no issues with the original, it may have something to do with the following two mods: "Morecompany" or "SpectateEnemies"
> 
> The camera freeze problem often occurs when observing an enemy or teammate after death, switching back and forth, or looking at the same object for a long time causes the camera to be fixed, which causes the camera to get stuck even after being resurrected

I haven't encountered any issues with both of those mods so far - I'm not playing a lot with MoreCompany but I played a lot with SpectateEnemies and had no issues, so I don't think that is the case.

**Comment by Lauriichan** [comment] 2024-03-08 19:56
@rainbow137 Could u try 1.0.3 and see if that changed something?
And it seems like the Played with Feature is not the problem, so I guess it is related to the username fix patch

**Comment by Lauriichan** [comment] 2024-03-08 19:57
But so far I would also say that it is probably related to MoreCompany

**Comment by Sourceshard** [comment] 2024-03-08 20:15
> > Ahh I was having this issue as well and was trying to track it down. I will report back if this problem has disappeared for me.
> 
> Could you possibly provide a full mod list so I can check for similarities?

My modlist is not for the faint of heart. Its still WIP.
018e1fb6-ec52-9a1e-3174-0c892ab86af1

**Comment by Lauriichan** [comment] 2024-03-18 17:43
Closing this in favour of #5

**Closed as completed by Lauriichan** 2024-03-18 17:43 UTC
Labels: Bug, Duplicate, Incompatibility

**Comment by Lauriichan** [comment] 2024-03-19 14:31
Got fixed in 1.0.4, see #5 for more info
