### ISSUE TITLE
Friend Patches present in mod list causes immense instability and various unexpected errors.

### ISSUE THREAD

**Issue by Sourceshard** [Lauriichan/LC-FriendPatches#5] opened 2024-03-18 01:04 UTC
### Not a mod compatibility issue

- [X] I confirm that the my issue is not related to compatibility issues with another mod

### Mod version

Friend Patches 1.0.3

### Mod list

BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.3
Evaisa-LethalThings-0.9.4
notnotnotswipez-MoreCompany-1.8.1
x753-Mimics-2.4.1
Rune580-LethalCompany_InputUtils-0.7.1
sunnobunno-YippeeMod-1.2.4
EliteMasterEric-Coroner-1.6.2
NotAtomicBomb-TerminalApi-1.5.2
FlipMods-FasterItemDropship-1.2.1
IntegrityChaos-Diversity-2.0.3
kuba6000-LC_Masked_Fix-0.0.2
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
sfDesat-Orion-2.0.1
sfDesat-Aquatis-2.0.0
KayNetsua-E_Gypt_Moon-2.0.15
jockie-LethalExpansionCore-1.3.15
FlipMods-TooManyEmotes-2.0.5
Ozone-Runtime_Netcode_Patcher-0.2.5
IAmBatby-LethalLevelLoader-1.1.6
sfDesat-ExpansionAssets-1.1.0
taffyko-BetterSprayPaint-2.0.2
TwinDimensionalProductions-CoilHeadStare-1.0.9
LethalResonance-LETHALRESONANCE-4.2.3
FutureSavior-Hold_Scan_Button-1.1.1
akechii-DiscountAlert-2.3.0
KodiCraft-TermSpeak-1.1.0
darmuh-ghostCodes-1.5.1
Zingar-Atlas_Abyss-1.1.8
Boniato-Ganimedes-2.1.0
AudioKnight-StarlancerMoons-1.3.0
Alice-ScarletDevilMansion-1.3.6
AinaVT-LethalConfig-1.3.4
Solar32-PerformanceEnhancer-1.3.6
Hypick-BetterShotgun-1.4.6
mrov-LethalRichPresence-0.5.8
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-2.1.6
Pinta-PintoBoy-1.0.4
MrHydralisk-EnhancedRadarBooster-1.6.2
Justice69-ImmersiveScraps-1.2.0
bigmcnugget-VanillaContentExpansion-0.1.8
Spyci-CozyImprovements-1.2.2
Woecust-Immersive_Visor-0.3.3
Beauver-ExtraTerminalCommands-1.5.0
TheLore-TerminalShortcuts-1.0.1
joejoejoe-LCLightsStartOffMod-2.0.5
DeathGOD7-LCItemValue-1.0.0
Hardy-LCMaxSoundsFix-1.1.0
monkes_mods-JumpDelayPatch-1.0.1
FlipMods-MoreBlood-1.0.2
Hexnet111-SuitSaver-1.1.4
NutNutty-SellTracker-1.2.1
extraes-LethalLoudnessMeter-1.0.2
Zaggy1024-PathfindingLagFix-1.2.1
Zaggy1024-OpenBodyCams-1.3.0
Swaggies-BetterEXP-1.2.2
PXC-EnhancedSpectator-1.0.5
AllToasters-SpectateEnemies-2.3.1
La_chips-AutoCompanyBuilding-1.2.0
Major_And_Skiz-MoreInteriors-2.5.0
Scintesto-Monster_Plushies-1.1.2
bandaidroo-BandaidsMegaCosmetics-1.1.0
Beepsterr-AnnounceMoonChange-1.0.1
Hamunii-JetpackWarning-2.2.0
femboytv-LethalPosters-1.2.0
Cades-BestiaryPosterTips-1.0.1
bozzobrain-BetterDoorWarning-1.0.0
Kittenji-Groan_Tube_Scrap-1.0.1
stefan750-LCUltrawide-1.1.1
PlainBen-BensCosmetics-1.2.0
Smxrez-SmoreCosmetics-1.7.0
Hamunii-JetpackFallFix-2.0.1
Hamunii-JetpacksCarryBigItems-1.0.2
MrHydralisk-EnhancedLockpicker-1.1.4
MrHydralisk-MajorityVote-1.1.0
quackandcheese-ToggleMute-1.3.1
Dev1A3-ScannableCodes-1.0.2
SillySquad-Arachnophilia-1.7.0
ohotdog-LootableMusicTapes-1.0.1
zealsprince-Malfunctions-1.8.2
RedCrowbar-BuffedPresents-0.0.5
souper194-HDVanillaPosters-1.0.5
LeKAKiD-SignalTranslatorAligner-1.1.0
Zaggy1024-NutcrackerFixes-1.2.2
fumiko-CullFactory-0.9.2
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
qwbarch-Mirage-1.1.0
Coppertiel-MaskedEnemyOverhaulFork-3.1.990
kyxino-LethalModManager-0.0.2
veri-ShipWindows-2.0.2
AudioKnight-StarlancerAIFix-3.3.0
mrov-UnlockableDefaults-0.0.1
taffyko-QuickQuitToMenu-1.0.1
ViViKo-TwoHandedStorage-1.0.0
CTNOriginals-OuterDoorButtons-1.0.2
Dantor-Dantors_Mental_Hospital-1.2.2
NiaNation-AbsasCosmetics-1.2.3
fonnymunkey-SimpleHats-1.0.0
Hexa-Hexas_Cosmetics-0.0.2
ZTK-ZTKCosmetics-2.0.0
loaforc-FacilityMeltdown-2.4.7
BGN-PizzaTowerEscapeMusic-2.3.0
den-Meltdown_Chance-2.3.0
LethalMoonTeam-Ether-1.6.7
Kittenji-NavMeshInCompany-1.0.2
Kittenji-Herobrine-1.3.1
LethalMatt-Outpost_31-1.2.0
Zingar-SecretLabs-3.3.7
Badham_Mods-SCPFoundationDungeon-3.0.0
jaspercreations-Scopophobia-1.1.1
AudioKnight-StarlancerMusic-1.1.0
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.6
mrov-WeatherTweaks-0.4.6
Speakers-IndieGameScrap-1.2.0
Segich-BodyCam_Reshade-1.0.1
quackandcheese-MirrorDecor-1.3.2
x753-More_Suits-1.4.1
ViViKo-MoreMaterials-1.3.2
ViViKo-MedicSuit-1.0.2
AliCat-Drip_Suit-1.0.1
ArticFox_Monix-FelixAndFriendsScraps-1.2.0
loaforc-loaforcsSoundAPI-0.1.3
readboy_and_the_boys-brackensuit-1.0.2
Kirpichyov-EnemiesScanner-1.0.6
2Lethal4Company-SpringFactory-1.4.5
Tolian-EchoReach-0.3.7
willis81808-LethalSettings-1.4.0
Sconeys-abandonedcompanyassets-0.12.55
mrov-LightsOut-0.0.6
malco-Lategame_Upgrades-3.3.1
Piggy-LC_Office-1.1.17
Hamster-LethalPipeRemoval-1.5.0
readthisifbad-SnatchinBracken-1.4.5
SylviBlossom-SmartItemSaving-1.2.1
mrov-TerminalFormatter-0.0.11
EladNLG-EladsHUD-1.2.1
Bob123-Haunted_Harpist-1.2.9
SZAKI-EnemyFix-1.0.0
Ccode_lang-SirenHead-1.2.2
Sligili-More_Emotes-1.3.3
taffyko-NiceChat-1.2.4
PostMortem-BetterLightning-1.0.3
IntegrityChaos-LCCutscene-1.0.0
broiiler-inacraft_cosmetics_megapack-1.0.1
happyfrosty-FrostyCosmetics-1.0.7
nerdcat-SillyCosmetics-1.8.0
TeamClark-SCP_Foundation_Suit-1.1.0
Tolian-Maritopia-0.4.9
gamendegamer-Lethal_Admin-1.5.0
Graze-HostOnlyPurchase-1.0.0
Glitch-RankFix-1.0.2
Dev1A3-LobbyInviteOnly-1.0.7
ShaosilGaming-FlashlightFix-1.1.2
FlipMods-ReservedItemSlotCore-2.0.9
FlipMods-ReservedWalkieSlot-2.0.2
FlipMods-ReservedFlashlightSlot-2.0.2
FlipMods-ReservedSprayPaintSlot-1.1.1
Suskitech-AlwaysHearActiveWalkies-1.4.4
FlipMods-BetterStamina-1.3.2
HGG-JigglePhysicsPlugin-1.1.2
Mhz-MoreHead-1.2.6
zealsprince-Locker-1.1.0
AmesBoys-ImmortalSnail-0.7.3
x753-Peepers-0.9.6
PloufJPEG-CompanyCreatures-0.2.0
Frack9-DarkMist-1.3.0
xCeezy-LethalEscape-0.8.5
SylviBlossom-TerminalConflictFix-1.2.2
pacoito-StoreRotationConfig-1.1.1
SweetOnion-LethalSnap-1.5.5
consequential-Oxygen-1.4.0
Kittenji-Pinya-1.0.2
TeamCosmic-GoldenShovel-1.1.2
SolidStone-ShockwaveDroneEnemy-0.3.0
Fredolx-MeteoMultiplier-1.1.3
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
IsAmMonkes-BetterMenuSong-1.0.0
Wolf11221-SpaceShipDoor-1.0.1
IntegrityChaos-GraphicsAPI-1.0.0
ShaosilGaming-GeneralImprovements-1.1.11
Tolian-PsychSanctum-0.3.0
FlipMods-HotbarPlus-1.5.9
Magic_Wesley-Wesleys_Moons-3.0.31
XuVELD-HotbarRD-1.1.0
Rocksnotch-ShovelFix-1.1.0
sfDesat-ViewExtension-1.1.0
sfDesat-Celest-1.0.6
Sigurd-CSync-3.1.1
LethalMatt-Bozoros-0.1.8
Scoliosis-StrangerThingsMod-0.0.32
Verity-TooManySuits-1.0.5
RT0405-TooManySuitsInWorldButtons-1.0.1
404_Dom-Doms_Basic_Suit_Colors-1.4.4
Uprank-Rush_Of_Adrenaline-1.0.0
Danos-LethalStats-0.9.2
CTNOriginals-CrossHair-1.1.0
MegaPiggy-InsanityMeter-1.0.0
LegoMaster3650-FairGiants-1.0.0
e3s1-BetterLadders-1.4.2
Fredolx-SignalTranslatorUpgrade-1.0.0
blink9803-DimmingFlashlights-1.0.1
Ozone-BepInUtils-1.2.1
TheFluff-FairAI-1.3.3
Rolevote-The_Fiend-1.0.5
Toskan4134-LethalRegeneration-1.3.0
XuXiaolan-TheGiantSpecimens-1.6.2
TestAccount666-ScannableTools-1.0.4
Nikki-NikkisCosmeticKingdom-2.0.0
Metrollen-FNAF_Moon-1.1.4
TheFluff-GetLootForKills-1.2.3
DrinkableWater-Brutal_Company_Minus-0.10.7
LethalSex-LethalSex_Core-1.2.5
LethalSex-LethalSanity-1.3.1
kidcudilovers-CudisRealisticSuits-1.0.0
Dwarggo-Fashion_Company-1.3.1
Dunn-HEV_Suit-1.2.0
FEB-SCP_Suits-1.1.0
Kats-Some_Suits-1.0.6
ViViKo-BreakingBadHazmatSuit-1.0.3
Sparble-FacelessStalker-1.0.6
Ceelery-Kast-1.0.3
MrUnrealTeam-SchoolMoon-1.1.5
MrUnrealTeam-SchoolDungeon-1.1.0
RosiePies-Rosies_Moons-1.0.5
mrov-IntroTweaks-1.0.0
sfDesat-Celestial_Tint-1.1.4
anormaltwig-LateCompany-1.0.11
AgentRev-ShootableMouthDogs-1.0.1
SlushyRH-FreeeeeeMoooooons-1.0.1
Tolian-Zenit-0.1.0
Tolian-Nyx-0.1.3
Tolian-Harloth-0.1.6
MusicalSleep-SleepsDungeon-1.0.1
Guodan-Crest-1.1.0
Asc3nt-EnhancedTZP-1.1.1
mattymatty-AsyncLoggers-1.2.4
TestAccount666-AnnounceMoonAndWeatherChange-1.0.0
TestAccount666-ForceGrabItem-1.1.0
TestAccount666-NoPocketSounds-1.0.1
TestAccount666-EntranceExitTipChanger-2.2.2
FlipMods-ReservedUtilitySlot-1.0.3
FlipMods-ReservedWeaponSlot-1.1.2
TKronix-DoorlessStorage-1.0.0
Garf-MissileTurrets-1.3.0
BatTeam-LethalFashion-1.0.6
Refract-LethalLevelLoaderFixed-1.1.0
mrov-UnlockOnStart-0.6.3

### Describe what happend

Literally any action in the game seems to trigger one of 2 responses.

1. The game frames suddenly drop, the game stutters, regains stability and then proceeds to immediately crash to desktop.

2. On lever pull the game freezes for the host. It becomes unresponsive while other players can still access the menu. The game then crashes to desktop after a short amount of time.

Because "Friend Patches" seems to replace the character frequently, any mod or process that expects no change to occur will fail. Anything tied to the model, whether it be cameras, sounds, emotes.

One of my errors with it saw the dissonance sound logs gain over 60+ new entries in seconds.

### Reproduction steps

- If the mod pack is too big to test, disable the lethal level loader and all associated mods. (Still occurs without it)
- Load modpack. Play with at least 2 players on Steam.
- After several landings and takeoffs the game will self-destruct and crash.
- Various error messages are caused. ( I have only had one crash that showed the true problem)
- remove Friend Patches, and every problem goes away.

### Expected behavior

No crashes, player name is checked and updated as necessary.

### Media

https://cdn.discordapp.com/attachments/1184362437550555176/1219082892450201610/image.png?ex=660a026b&is=65f78d6b&hm=d2fdb4a5b4910a81f728c3b5a7f68415c17c40a867e887bba9842f93d625e305&

https://cdn.discordapp.com/attachments/1184362437550555176/1219082892764905563/Screenshot_2024-03-17_092950.png?ex=660a026b&is=65f78d6b&hm=82d4a04ec81c17b42a371aa2943610463b241f16bc0fcf8bce03f5ea2fcc2db1&

[message (10).txt](https://github.com/Lauriichan/LC-FriendPatches/files/14629606/message.10.txt)

### Additional Information

R2 Mod Man Code for Shattered Company

018e4f0e-c464-864d-099f-bdef2d0c95af

**Comment by Sourceshard** [comment] 2024-03-18 01:06
To add. When the Steam friend feature is enabled in the config the spectator camera can fail to properly track players and monsters.

**Comment by DropDaDeuce** [comment] 2024-03-18 01:15
My friends and I were also experiencing crashes with FriendPatches enabled.
For us it seemed to only crash when someone was in spectator mode and we started the ship to leave the moon. But we only played through 2 crashes before giving up for the night, so I'm not sure what else could trigger a crash.
When it crashed, it crashed for all players.
Similar to Sourceshard, I also noticed in the logs the dissonance sound logs.
Once FriendPatches was disabled we stopped crashing.

**My mod list:**
BepInEx-BepInExPack-5.4.2100
x753-More_Suits-1.4.1
sunnobunno-YippeeMod-1.2.4
RickArg-Helmet_Cameras-2.1.5
x753-Mimics-2.4.1
EliteMasterEric-Coroner-1.6.2
TeamClark-ODST_Suit-1.0.0
OnePeak-Low_Budget_One_Piece_suits-0.5.1
Monkeytype-HideChat-1.0.0
NomnomAB-RollingGiant-2.5.2
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.3
Evaisa-LethalThings-0.9.4
Frack9-DarkMist-1.3.0
Verity-TooManySuits-1.0.5
Suskitech-AlwaysHearActiveWalkies-1.4.4
Caseuhdeeyuh-MolesterLootBug-1.1.0
Sligili-More_Emotes-1.3.3
tinyhoot-ShipLoot-1.0.0
Drakorle-MoreItems-1.0.2
sfDesat-Orion-2.0.1
sfDesat-Aquatis-2.0.1
Hexnet111-SuitSaver-1.1.4
thomas-AlwaysShowClock-1.0.0
TwinDimensionalProductions-CoilHeadStare-1.0.9
UnofficialJhonPlant-HiddenWeather-1.0.1
IntegrityChaos-Diversity-2.0.3
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
Norman-GlowStickSuits-1.0.4
Team_Waluigi-WaluigiSuit-0.0.3
Festive_Arms-FNAF_Suits-2.0.0
TeamClark-Vault_Boy_Suit-1.0.0
TeamClark-CombineEliteSuit-1.0.2
ViViKo-AmongUsSuits-1.0.2
DCBlack-Ghost_Buster_Uniform-1.1.5
Dunn-HEV_Suit-1.2.0
Booner-Bracken_Suit-1.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
boko-DerangedCompany-0.3.0
Kittenji-LaserPointerDetonator-1.0.0
Sakura-LandminesForAll-1.0.1
BatTeam-LethalFashion-1.0.6
Coomfy-CoomfyDungeon-1.0.12 - **Disabled**
notnotnotswipez-MoreCompany-1.8.1
Burrvuhvurr-ComedyAndTragedyMasks-1.0.1
stefan750-LCUltrawide-1.1.1
SenpaiTeam-VenomSuit-1.0.0
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.2.0
Rune580-LethalCompany_InputUtils-0.7.1
FlipMods-TooManyEmotes-2.0.5
AinaVT-LethalConfig-1.3.4
ViViKo-BetterDecorPlacement-1.2.1
Froze-LCConductivityRework-1.0.2
willis81808-LethalSettings-1.4.0
LethalResonance-LETHALRESONANCE-4.2.3
FlipMods-ObjectVolumeController-1.0.4
IAmBatby-LethalLevelLoader-1.1.6
IntegrityChaos-GraphicsAPI-1.0.0
IntegrityChaos-LCCutscene-1.0.0
loaforc-loaforcsSoundAPI-0.1.3
Hardy-LCMaxSoundsFix-1.1.0
AllToasters-SpectateEnemies-2.3.1
jaspercreations-Scopophobia-1.1.1
F4ilS4fe-MaskTheDead-1.0.5
Rolevote-The_Fiend-1.0.5
Coppertiel-MaskedEnemyOverhaulFork-3.1.990
qwbarch-BarchLib-1.0.0
Bobbie-NAudio-2.2.2
Bobbie-UniTask-2.5.0
qwbarch-Mirage-1.1.0
SZAKI-EnemyFix-1.0.0
Bobbie-FixRPCLag-1.0.1
ShaosilGaming-GeneralImprovements-1.1.11
Sparble-FacelessStalker-1.0.7
mattymatty-AsyncLoggers-1.2.6
Ccode_lang-SirenHead-1.2.2
XuXiaolan-TheGiantSpecimens-1.6.3
FlipMods-ReservedItemSlotCore-2.0.9
FlipMods-ReservedFlashlightSlot-2.0.2
FlipMods-ReservedWalkieSlot-2.0.2
anormaltwig-LateCompany-1.0.12
Lauriichan-FriendPatches-1.0.3
Blorb-WeatherMultipliers-1.1.0
Refract-LethalLevelLoaderFixed-1.1.0

**Added after FriendPatches was removed, but is still on my current modlist:**
sfDesat-ViewExtension-1.1.0
BananaPuncher714-LethalQuantities-1.2.8
EypoRage-EypoNoiseSuppression-1.0.0
Kittenji-NavMeshInCompany-1.0.2
Kittenji-Herobrine-1.3.1

**My r2modman Mod Profile:**
018e4f19-7b1e-b65f-a188-9b0fdbaf6da0

**Comment by Fl4sHNoX** [comment] 2024-03-18 14:50
+1 

Having the same issues with my modpack:

> "BepInEx-BepInExPack-5.4.2100",
        "2018-LC_API-3.4.5",
        "Evaisa-HookGenPatcher-0.0.5",
        "Evaisa-LethalLib-0.14.2",
        "xilophor-LethalNetworkAPI-2.1.6",
        "Rune580-LethalCompany_InputUtils-0.7.1",
        "Ozone-Runtime_Netcode_Patcher-0.2.5",
        "NiceHairs-NuclearLib-1.0.4",
        "LethalAPI-LethalAPI_Terminal-1.0.1",
        "NotAtomicBomb-TerminalApi-1.5.2",
        "Lordfirespeed-OdinSerializer-2022.11.9",
        "Bobbie-UniTask-2.5.0",
        "Bobbie-NAudio-2.2.2",
        "qwbarch-BarchLib-1.0.0",
        "AinaVT-LethalConfig-1.3.4",
        "AMRV-ConfigurableCompany-3.1.0",
        "AMRV-LethalCompanyVariables-1.9.0",
        "Sigurd-CSync-3.1.1",
        "EliteMasterEric-CleanerLogs-1.0.0",
        "mattymatty-AsyncLoggers-1.2.1",
        "Owen3H-IntroTweaks-1.5.0",
        "AdiBTW-Loadstone-0.0.2",
        "taffyko-QuickQuitToMenu-1.0.1",
        "SylviBlossom-TerminalConflictFix-1.2.1",
        "Hardy-LCMaxSoundsFix-1.1.0",
        "Bobbie-FixRPCLag-1.0.1",
        "Zaggy1024-PathfindingLagFix-1.2.1",
        "EliteMasterEric-SlimeTamingFix-1.0.2",
        "Zaggy1024-NutcrackerFixes-1.2.2",
        "raydenoir-HitboxesFix-1.0.0",
        "TheBeeTeam-LandmineFix-1.0.1",
        "ShaosilGaming-FlashlightFix-1.1.2",
        "ViViKo-ItemClippingFix-1.1.4",
        "FutureSavior-Boombox_Sync_Fix-1.1.2",
        "itsmeowdev-DoorFix-1.0.0",
        "bozzobrain-BetterDoorWarning-1.0.0",
        "Hamunii-JetpackFallFix-2.0.1",
        "Hamunii-JetpackWarning-2.2.0",
        "Invertigo-JetpackHandling-1.0.3",
        "thej01-DynamicFallDamage-1.0.0",
        "thej01-LethalWeight-1.0.2",
        "TREEPDEEP-JustJump-1.0.1",
        "Lauriichan-FriendPatches-1.0.3",
        "freesnow-CollectYourDead-1.0.3",
        "BlueAmulet-NameFix-1.0.1",
        "wallen-ChangeName-1.0.0",
        "taffyko-NiceChat-1.2.4",
        "Glitch-RankFix-1.0.2",
        "MoonJuice-BuyRateSettings-1.3.2",
        "BlueAmulet-LCBetterClock-1.0.3",
        "ButteryStancakes-AccurateStaminaDisplay-2.0.1",
        "lukeprime-CrouchHUD-1.0.0",
        "Piggy-ShowCapacity-1.0.9",
        "FutureSavior-Hold_Scan_Button-1.1.1",
        "LeKAKiD-SignalTranslatorAligner-1.1.0",
        "taffyko-BetterSprayPaint-2.0.2",
        "Hexi-HexiBetterShotgun-0.3.3",
        "axd1x8a-LCAmmoCheck-1.1.1",
        "e3s1-BetterLadders-1.4.2",
        "pencels-FasterLadders-1.0.2",
        "riverbible-TZPHealingCustom-1.0.0",
        "SlightlyInteractive-TurretDownTime-0.1.0",
        "Hamster-LethalPipeRemoval-1.4.3",
        "veri-ShipWindows-2.0.2",
        "Glitch-NoPropShadows-1.0.1",
        "CatsArmy-SpaceSunShine-1.3.0",
        "fumiko-CullFactory-0.9.2",
        "Pooble-LCBetterSaves-1.7.3",
        "stefan750-LCUltrawide-1.1.1",
        "notnotnotswipez-MoreCompany-1.8.1",
        "DaXcess-NoMoreCompanyLogo-1.0.0",
        "Ryokune-Better_Lobbies-1.1.1",
        "Dev1A3-RecentlyPlayedWith-1.0.3",
        "poogle-GoAwayModList-1.0.1",
        "HolographicWings-LethalExpansion-1.3.45",
        "jockie-LethalExpansionCore-1.3.15",
        "bigmcnugget-VanillaContentExpansion-0.1.8",
        "IAmBatby-LethalLevelLoader-1.1.6",
        "Refract-LethalLevelLoaderFixed-1.1.0",
        "ShaosilGaming-GeneralImprovements-1.1.11",
        "Spyci-CozyImprovements-1.2.2",
        "Karster-Light_Switch_Scan_Node-1.0.1",
        "TestAccount666-ScannableTools-1.0.4",
        "HectorAlligator-Solos_Ring_Compass_TWEAKED-1.0.2",
        "Dev1A3-ScannableCodes-1.0.2",
        "Suki-LCTerminalMultiCodes-1.0.0",
        "TestAccount666-AnnounceMoonAndWeatherChange-1.0.0",
        "JulianMods-OpenMonitors-1.0.5",
        "saint_kendrick-Lethal_Doors-1.0.4",
        "SillySquad-BetterTotalScrap-1.1.1",
        "NutNutty-SellTracker-1.2.1",
        "Hypick-AdrenalineRush-1.0.1",
        "PXC-EnhancedSpectator-1.0.5",
        "AllToasters-SpectateEnemies-2.3.1",
        "dummy-LetTheDeadRest-1.0.0",
        "MrHydralisk-MajorityVote-1.1.0",
        "EliteMasterEric-Coroner-1.6.2",
        "RugbugRedfern-Skinwalkers-4.0.3",
        "Exverge-BetterSkinwalkers-0.2.0",
        "qwbarch-Mirage-1.1.0",
        "Coppertiel-MaskedEnemyOverhaulFork-3.1.990",
        "Piggy-MaskedAIRevamp-0.2.1",
        "OE_Tweaks-Possessed_Masks-2.0.4",
        "SillySquad-TakeThatMaskOff-2.1.6",
        "kuba6000-LC_Masked_Fix-0.0.2",
        "x753-Mimics-2.4.1",
        "LegoMaster3650-FairGiants-1.0.0",
        "IntegrityChaos-GraphicsAPI-1.0.0",
        "IntegrityChaos-LCCutscene-1.0.0",
        "IntegrityChaos-Diversity-2.0.3",
        "thisMicki-BrackenFavRoom-0.1.9",
        "Piggy-JesterStompShake-1.0.8",
        "SillySquad-Arachnophilia-1.7.0",
        "Rikoun-HoarderBudcopy-1.0.0",
        "NiceHairs-Symbiosis-1.0.5",
        "TheFluff-FairAI-1.3.3",
        "alipali-Lethal_Company_Ordnance_Disposal-1.0.3",
        "Financier-GhostGirlFearReset-1.0.1",
        "TwinDimensionalProductions-CoilHeadStare-1.0.9",
        "Goobius-Scary_Coil_Head-0.5.1",
        "Krild-CoilheadDontOpenDoors-1.0.0",
        "Evaisa-LethalThings-0.9.4",
        "Cobster-FireExitLadders-1.0.1",
        "FlipMods-FasterItemDropship-1.2.1",
        "FlipMods-HotbarPlus-1.5.7",
        "FlipMods-ReservedItemSlotCore-2.0.6",
        "FlipMods-ReservedFlashlightSlot-2.0.1",
        "FlipMods-ReservedWalkieSlot-2.0.1",
        "FlipMods-ReservedSprayPaintSlot-1.1.0",
        "FlipMods-ObjectVolumeController-1.0.4",
        "dummy-FocusedWalkieTalkieVoices-0.0.1",
        "mrov-WeatherTweaks-0.4.6",
        "Blorb-WeatherMultipliers-1.1.0",
        "Froze-LCConductivityRework-1.0.2",
        "PostMortem-BetterLightning-1.0.3",
        "Vizashiro-PreventRandomLightningDeaths-1.0.3",
        "CTMods-KarmaForBeingAnnoying-1.1.0",
        "Justice69-ImmersiveScraps-1.2.0",
        "Keyble-Nerd_Scraps-1.1.4",
        "eXish-Batteries-1.0.5",
        "Scintesto-Monster_Plushies-1.1.2",
        "Jordo-NeedyCats-1.2.1",
        "RedCrowbar-BuffedPresents-0.0.5",
        "Sconeys-abandonedcompanyassets-0.12.55",
        "KawaiiBone-Remnants-1.2.3",
        "Axeron-SellYourStuff-1.0.1",
        "x753-More_Suits-1.4.1",
        "Shootgang-Some_Buyable_Suits-1.8.0",
        "BatTeam-LethalFashion-1.0.6",
        "Hexnet111-SuitSaver-1.1.4",
        "bandaidroo-BandaidsMegaCosmetics-1.1.0",
        "Insomniax-InsomniaxCosmetics-1.2.0",
        "companyemployee-EquipmentCompany-1.3.0",
        "PlainBen-BensCosmetics-1.2.0",
        "Smxrez-SmoreCosmetics-1.7.0",
        "UnLuckyNikolay-RandomCosmetics-1.5.0",
        "BigBadPigeon-PigeonsCosmeticsAddon-1.0.4",
        "KlutzyBubbles-BetterEmotes-1.4.5",
        "femboytv-LethalPosters-1.2.0",
        "Cades-BestiaryPosterTips-1.0.1",
        "femboytv-LethalPaintings-1.2.0",
        "Pedr9vskCray-Minecraft_Paintings-1.0.0",
        "Rattenbonkers-TVLoader-1.1.1",
        "Asc3nt-TomJerryTVpack-1.0.0",
        "no00ob-LCSoundTool-1.5.1",
        "Clementinise-CustomSounds-2.3.2",
        "Bombers_Team-Grampas_Groovy_Gramophone-1.2.0",
        "kRYstall9-FastSwitchPlayerViewInRadar-1.3.2",
        "MrHydralisk-EnhancedLockpicker-1.1.4",
        "Piggy-RadarZoom-1.0.1",
        "ZG-ScalingStartCredits-1.0.6",
        "Coomfy-CoomfyDungeon-1.0.12",
        "Zaggy1024-OpenBodyCams-1.3.0",
        "fumiko-BetterMonitor-0.1.3",
        "red_eye-LethalAutocomplete-0.4.5",
        "Beauver-ExtraTerminalCommands-1.5.0",
        "La_chips-AutoCompanyBuilding-1.2.0",
        "skidz-PoolRooms-0.1.18",
        "Dantor-Dantors_Mental_Hospital-1.2.0",
        "RosiePies-Rosies_Moons-1.0.2",
        "AudioKnight-StarlancerAIFix-3.3.0",
        "SylviBlossom-SmartItemSaving-1.2.1",
        "pacoito-StoreRotationConfig-1.1.1",
        "mrov-TerminalFormatter-0.0.11",
        "Spantle-ThrowEverything-0.4.1",
        "GuysNight-Balanced_Items-1.6.0"

**Comment by Fl4sHNoX** [comment] 2024-03-18 14:51
> To add. When the Steam friend feature is enabled in the config the spectator camera can fail to properly track players and monsters.

This sounds exactly like the issue I've been having for weeks!

**Comment by Lauriichan** [comment] 2024-03-18 17:30
> Because "Friend Patches" seems to replace the character frequently, any mod or process that expects no change to occur will fail. Anything tied to the model, whether it be cameras, sounds, emotes.
Friend patches doesn't change any models or anything, it only updates names and waits for Steam responses, this issue is not connected to Friend Patches but instead it is most likely a result of a incompatiblity.

You ticked the checkbox to confirm that it is not a result of a incompatibility so I'm guessing you were able to reproduce this behaviour with just Friend Patches installed?
Cause I've been using the mod since I made it and haven't had any issues since. No problems with emotes, spectator cameras or anything of that kind.
I'm thinking that this is not a direct issue of the mod but instead a incompatibility with another mod and I'm highly suspecting it to be either the Network Patcher library or MoreCompany so far.

This is basically a duplicate of #1

**Comment by Lauriichan** [comment] 2024-03-18 17:40
In case of your modlist it seems (after looking at the log) that 

> IntegrityChaos-Diversity-2.0.3

Is throwing errors sometimes and a couple errors of MoreCompany.
I don't know what this problem in general is about but so far I'm just thinking about a mod incompatibility here for reasons that I can't understand as I'm only updating text and sending a request to Steam to notify about players and listen to player updates.

**Comment by Lauriichan** [comment] 2024-03-18 17:55
After looking into everything again I am suspecting that a HUD patch of MoreCompany is the cause of this.
https://github.com/notnotnotswipez/MoreCompany/blob/master/MoreCompany/HudPatches.cs#L121

**Comment by Lauriichan** [comment] 2024-03-18 18:06
Might be fixed with 1.0.4 (see 0c1eb6f)

**Comment by DropDaDeuce** [comment] 2024-03-18 18:31
I'll test this out next time I play. Thank you for looking in to it!

**Comment by DropDaDeuce** [comment] 2024-03-18 23:45
Seems to be working, so far! Thank you.

**Comment by Lauriichan** [comment] 2024-03-19 14:29
Please make sure to test next time if everything works fine without any other mods installed, if it does then you are most likely talking about an incompatibility issue like it was the case this time. Thanks to everyone who reported this issue :) Now that it is fixed there hopefully won't be any incompatibility problems in the future but I can't guarantee it.
I'll close this issue for now, feel free to reopen it if it is still an issue with MoreCompany and 1.0.4

**Closed as completed** 2024-03-19 14:30 UTC
Labels: Bug, Incompatibility
